// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://spxxcarxcuedkwrsdten.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNweHhjYXJ4Y3VlZGt3cnNkdGVuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4NDI2MTAsImV4cCI6MjA3MzQxODYxMH0.TM4eiuhZ3Lozvm48PDW26FYw2xCnGQhIitJdU7G9lx0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});